#!/bin/sh
make
clear

# argv[1] = NUMBER OF PHILOSOPHERS
# argv[2] = DURATION(in millisecs) TO STAY ALIVE WITHOUT EATING
# argv[3] = DURATION EACH PHILOSOPHER MUST HOLD TWOR FORKS(EATING)
# argv[4] = DURATION EACH PHILOSOPHER MUST STAY SLEEPING(NOT EATING)
# argv[5] (optional) = NUMBER OF TIMES EACH PHILOSOPHER SHOULD EAT, THEN THE SIMULATION STOPS
./philosophers 10 400 200 200 10
make fclean

